src/ArchiveMVCnew/ArchivenewInfrastructure/Controllers/ReferencesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ArchivenewDomain.Model;
using ArchivenewInfrastructure;

namespace ArchivenewInfrastructure.Controllers
{
    public class ReferencesController : Controller
    {
        private readonly DbfacultyArchivenewContext _context;

        public ReferencesController(DbfacultyArchivenewContext context)
        {
            _context = context;
        }

        
        public async Task<IActionResult> ReferenceIndex(string searchTerm, string searchBy)
        {
            IQueryable<Date> dates = _context.Dates;

            if (!string.IsNullOrEmpty(searchTerm) && !string.IsNullOrEmpty(searchBy))
            {
                switch (searchBy)
                {
                    case "FullName":
                        dates = dates.Where(d => d.FullName.Contains(searchTerm));
                        break;
                    case "Title":
                        dates = dates.Where(d => d.Title.Contains(searchTerm));
                        break;
                    case "Faculty":
                        dates = dates.Where(d => d.Faculty.Contains(searchTerm));
                        break;
                    default:
                        break;
                }

                var dateList = await dates.ToListAsync();
                return View(dateList);
            }

            
            return View(new List<Date>());
        }



        private bool ReferenceExists(int id)
        {
            return _context.References.Any(e => e.ReferenceId == id);
        }
    }
}

src/ArchiveMVCnew/ArchivenewInfrastructure/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ArchivenewInfrastructure</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap_state.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ArchivenewInfrastructure.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Dates" asp-action="Index"><b>FacultyArchive</b></a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index"><b>Home</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy"><b>Privacy</b></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="References" asp-action="ReferenceIndex"><b>Search</b></a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()


        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ArchivenewInfrastructure - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
    

</body>
</html>